spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_db
    username: appuser
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    use-new-id-generator-mappings: false  #`hibernate_sequence' doesn't exist
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true

server:
  port: 8081
  error:
    include-message: always